[project]
name = "rEAMember"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docopt",
    "pypng",
    "seaborn",
    "numpy",
    "pandas",
    "matplotlib",
    "protobuf",
    "h5py",
    "tqdm",
    "joblib",
    "torch>=2.7.0",
    "click>=8.2.1",
    "omegaconf>=2.3.0",
    "torchvision>=0.22.1",
    "pytorch-lightning>=2.5.2",
    "ipykernel>=6.29.5",
    "tensorboard==2.20.0",
    "scikit-learn>=1.7.0",
    "plotly>=6.1.2",
    "kaleido>=1.0.0",
    "pdoc>=15.0.4",
    "rich-click>=1.8.9",
    "nbformat>=5.10.4",
    "transformers>=4.57.0",
    "datasets>=4.1.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
