app:
  dataset: FashionMNIST
  modality: image
  column: null
  crossval:
    folds: 2
    seed: 42
neural:
  latent_dim:
  - 256
  epochs: 50
  batch_size: 64
  learning_rate: 0.001
  patience: 7
  delta: 0.005
memory:
  noise_level: 0.0
  domain:
  - 2
  filling:
  - 0.8
  iota: 0.0
  kappa: 0.0
  xi: 0.0
  sigma: 0.1
  m: null
