app:
  dataset: npvinHnivqn/EnglishDictionary
  column: word
  modality: text
  seed: 42
  noise: 0.1

neural:
  latent_dim: [1024]

memory:
  domain: [4096, 8192, 16384]
  batch_size: [64, 32, 16]
  filling: [1.0]
  iota: [0.0, 0.1]
  kappa: [0.0]
  xi: [0, 100, 200]
  sigma: [0.01, 0.06, 0.1]