app:
  dataset: npvinHnivqn/EnglishDictionary
  column: definition
  modality: text

neural:
  latent_dim: [1024]

memory:
  domain: [4096, 8192, 16384]
  batch_size: 16
  filling: [1.0]
  iota: [0.0, 0.1]
  kappa: [0.0, 0.1]
  xi: [0]
  sigma: [0.1, 0.2]