app:
  dataset: npvinHnivqn/EnglishDictionary
  column: definition
  modality: text

neural:
  latent_dim: [1024]

memory:
  domain: [16384]
  batch_size: 8
  filling: [1.0]
  iota: 0.0
  kappa: 0.0
  xi: 0.0
  sigma: 0.1