app:
  dataset: npvinHnivqn/EnglishDictionary
  column: word
  modality: text

neural:
  latent_dim: [1024]

memory:
  domain: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  batch_size: 512
  filling: [1.0]
  iota: 0.0
  kappa: 0.0
  xi: 0.0
  sigma: 0.1