app:
  dataset: npvinHnivqn/EnglishDictionary
  column: definition
  modality: text
  seed: 42
  noise: 0.003

neural:
  latent_dim: [1024]

memory:
  domain: [4096, 8192, 16384]
  batch_size: [64, 32, 16]
  filling: [1.0]
  iota: [0.0, 0.1, 0.5, 1.0]
  kappa: [0.0, 0.5, 1.0]
  xi: [0, 30, 50]
  sigma: [0.01, 0.06, 0.1]
